dist: trusty
sudo: required

env:
    global:
        - HUGO_VERSION=0.37.1

install:
    - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
    - sudo dpkg -i /tmp/hugo.deb

script:
    - hugo

deploy:
    provider: pages
    skip-cleanup: true
    # Publish the directory `public`.
    local-dir: public
    # Use the github token stored in the travis environment
    github_token: $GITHUB_TOKEN
    on:
        branch: travis
