# Must end with '/'
baseURL = "https://jur0.github.io/jjk-web/"

languageCode = "en-us"
title = "JJK Crypto Assets"
paginate = 5

# Generate robots.txt (by default it allows to crawl everything).
enableRobotsTXT = true

[author]
    name = "JJK Crypto Assets"
    email = "info@jjkcryptoassets.com"

[params]
    debug = true

    date_format = "January 2, 2006"
    time_format = "15:04"

    description = "Diversified and actively managed portfolio of digital assets"

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio"
    weight = 2

[[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[outputs]
    home = [ "HTML", "CSS", "RSS" ]
    section = [ "HTML", "RSS" ]

[outputFormats.CSS]
    # Change default generated css file to style.css
    baseName = "style"

preserveTaxonomyNames = true

[taxonomies]
    category = "categories"
    tag = "tags"
